import pygame
import algo
#pygame can be install by writing pip install pygame into cmd
#to open cmd search it after pressing the windows icon

pygame.init() #initialize pygame
pygame.display.set_caption("Sudoku Solver")
screen = pygame.display.set_mode((560, 620)) #560 and 600 chosen because 560 is divisible by 9 and 
                                             #for 620 we will use a bit of the bottom for buttons (60 pixels)
 
def button(screen, position, text): # normal number squares
    font = pygame.font.SysFont("Arial", 50)
    text_render = font.render(text, 1, (0, 0, 0)) #black color of text
    x, y = position
    pygame.draw.rect(screen, (255, 255, 255), (x, y, 60 , 60))
    return screen.blit(text_render, (x, y))
 
def extra_button(screen, position, text): # for the boxes like reset and GO!
    font = pygame.font.SysFont("Arial", 30)
    text_render = font.render(text, 1, (255, 0, 0))
    x, y = position
    pygame.draw.rect(screen, (255, 255, 255), (x, y, 100 , 50))
    return screen.blit(text_render, (x, y))
 
def empty_buttons(): # to initialize the board
    global test1, b1,b2,b3,b3 ,b4 ,b5 ,b6 ,b7 ,b8 ,b9 ,b10,b11,b12,b13,b14,b15,b16,b17,b18,b19,b20,b21,b22,b23,b24,b25,b26,b27,b28,b29,b30,b31,b32,b33,b34,b35,b36,b37,b38,b39,b40,b41,b42,b43,b44,b45,b46,b47,b48,b49,b50,b51,b52,b53,b54,b55,b56,b57,b58,b59,b60,b61,b62,b63,b64,b65,b66,b67,b68,b69,b70,b71,b72,b73,b74,b75,b76,b77,b78,b79,b80,b81, reset, go
    b1 = button(screen, (000, 0), "0")
    b2 = button(screen, (62 , 0), "0")
    b3 = button(screen, (124, 0), "0")
    b4 = button(screen, (188, 0), "0")
    b5 = button(screen, (250, 0), "0")
    b6 = button(screen, (312, 0), "0")
    b7 = button(screen, (376, 0), "0")
    b8 = button(screen, (438, 0), "0")
    b9 = button(screen, (500, 0), "0")
    b10 = button(screen, (000, 62), "0")
    b11 = button(screen, (62 , 62), "0")
    b12 = button(screen, (124, 62), "0")
    b13 = button(screen, (188, 62), "0")
    b14 = button(screen, (250, 62), "0")
    b15 = button(screen, (312, 62), "0")
    b16 = button(screen, (376, 62), "0")
    b17 = button(screen, (438, 62), "0")
    b18 = button(screen, (500, 62), "0")
    b19 = button(screen, (000, 124), "0")
    b20 = button(screen, (62 , 124), "0")
    b21 = button(screen, (124, 124), "0")
    b22 = button(screen, (188, 124), "0")
    b23 = button(screen, (250, 124), "0")
    b24 = button(screen, (312, 124), "0")
    b25 = button(screen, (376, 124), "0")
    b26 = button(screen, (438, 124), "0")
    b27 = button(screen, (500, 124), "0")
    b28 = button(screen, (000, 188), "0")
    b29 = button(screen, (62 , 188), "0")
    b30 = button(screen, (124, 188), "0")
    b31 = button(screen, (188, 188), "0")
    b32 = button(screen, (250, 188), "0")
    b33 = button(screen, (312, 188), "0")
    b34 = button(screen, (376, 188), "0")
    b35 = button(screen, (438, 188), "0")
    b36 = button(screen, (500, 188), "0")
    b37 = button(screen, (000, 250), "0")
    b38 = button(screen, (62 , 250), "0")
    b39 = button(screen, (124, 250), "0")
    b40 = button(screen, (188, 250), "0")
    b41 = button(screen, (250, 250), "0")
    b42 = button(screen, (312, 250), "0")
    b43 = button(screen, (376, 250), "0")
    b44 = button(screen, (438, 250), "0")
    b45 = button(screen, (500, 250), "0")
    b46 = button(screen, (000, 312), "0")
    b47 = button(screen, (62 , 312), "0")
    b48 = button(screen, (124, 312), "0")
    b49 = button(screen, (188, 312), "0")
    b50 = button(screen, (250, 312), "0")
    b51 = button(screen, (312, 312), "0")
    b52 = button(screen, (376, 312), "0")
    b53 = button(screen, (438, 312), "0")
    b54 = button(screen, (500, 312), "0")
    b55 = button(screen, (000, 376), "0")
    b56 = button(screen, (62 , 376), "0")
    b57 = button(screen, (124, 376), "0")
    b58 = button(screen, (188, 376), "0")
    b59 = button(screen, (250, 376), "0")
    b60 = button(screen, (312, 376), "0")
    b61 = button(screen, (376, 376), "0")
    b62 = button(screen, (438, 376), "0")
    b63 = button(screen, (500, 376), "0")
    b64 = button(screen, (000, 438), "0")
    b65 = button(screen, (62 , 438), "0")
    b66 = button(screen, (124, 438), "0")
    b67 = button(screen, (188, 438), "0")
    b68 = button(screen, (250, 438), "0")
    b69 = button(screen, (312, 438), "0")
    b70 = button(screen, (376, 438), "0")
    b71 = button(screen, (438, 438), "0")
    b72 = button(screen, (500, 438), "0")
    b73 = button(screen, (000, 500), "0")
    b74 = button(screen, (62 , 500), "0")
    b75 = button(screen, (124, 500), "0")
    b76 = button(screen, (188, 500), "0")
    b77 = button(screen, (250, 500), "0")
    b78 = button(screen, (312, 500), "0")
    b79 = button(screen, (376, 500), "0")
    b80 = button(screen, (438, 500), "0")
    b81 = button(screen, (500, 500), "0")
    reset = extra_button(screen, (150,565), "RESET")
    go = extra_button(screen, (350,565), "   GO! ")
    test1 = extra_button(screen, (10,565), "Test 1")

def new_buttons(lst): # to update every time a new digit is entered
    global test1, b1,b2,b3,b3 ,b4 ,b5 ,b6 ,b7 ,b8 ,b9 ,b10,b11,b12,b13,b14,b15,b16,b17,b18,b19,b20,b21,b22,b23,b24,b25,b26,b27,b28,b29,b30,b31,b32,b33,b34,b35,b36,b37,b38,b39,b40,b41,b42,b43,b44,b45,b46,b47,b48,b49,b50,b51,b52,b53,b54,b55,b56,b57,b58,b59,b60,b61,b62,b63,b64,b65,b66,b67,b68,b69,b70,b71,b72,b73,b74,b75,b76,b77,b78,b79,b80,b81, reset, go
    b1 = button(screen, (000, 0), str(lst[0]))
    b2 = button(screen, (62 , 0), str(lst[1]))
    b3 = button(screen, (124, 0), str(lst[2]))
    b4 = button(screen, (188, 0), str(lst[3]))
    b5 = button(screen, (250, 0), str(lst[4]))
    b6 = button(screen, (312, 0), str(lst[5]))
    b7 = button(screen, (376, 0), str(lst[6]))
    b8 = button(screen, (438, 0), str(lst[7]))
    b9 = button(screen, (500, 0), str(lst[8]))
    b10 = button(screen, (000, 62), str(lst[9]))
    b11 = button(screen, (62 , 62), str(lst[10]))
    b12 = button(screen, (124, 62), str(lst[11]))
    b13 = button(screen, (188, 62), str(lst[12]))
    b14 = button(screen, (250, 62), str(lst[13]))
    b15 = button(screen, (312, 62), str(lst[14]))
    b16 = button(screen, (376, 62), str(lst[15]))
    b17 = button(screen, (438, 62), str(lst[16]))
    b18 = button(screen, (500, 62), str(lst[17]))
    b19 = button(screen, (000, 124), str(lst[18]))
    b20 = button(screen, (62 , 124), str(lst[19]))
    b21 = button(screen, (124, 124), str(lst[20]))
    b22 = button(screen, (188, 124), str(lst[21]))
    b23 = button(screen, (250, 124), str(lst[22]))
    b24 = button(screen, (312, 124), str(lst[23]))
    b25 = button(screen, (376, 124), str(lst[24]))
    b26 = button(screen, (438, 124), str(lst[25]))
    b27 = button(screen, (500, 124), str(lst[26]))
    b28 = button(screen, (000, 188), str(lst[27]))
    b29 = button(screen, (62 , 188), str(lst[28]))
    b30 = button(screen, (124, 188), str(lst[29]))
    b31 = button(screen, (188, 188), str(lst[30]))
    b32 = button(screen, (250, 188), str(lst[31]))
    b33 = button(screen, (312, 188), str(lst[32]))
    b34 = button(screen, (376, 188), str(lst[33]))
    b35 = button(screen, (438, 188), str(lst[34]))
    b36 = button(screen, (500, 188), str(lst[35]))
    b37 = button(screen, (000, 250), str(lst[36]))
    b38 = button(screen, (62 , 250), str(lst[37]))
    b39 = button(screen, (124, 250), str(lst[38]))
    b40 = button(screen, (188, 250), str(lst[39]))
    b41 = button(screen, (250, 250), str(lst[40]))
    b42 = button(screen, (312, 250), str(lst[41]))
    b43 = button(screen, (376, 250), str(lst[42]))
    b44 = button(screen, (438, 250), str(lst[43]))
    b45 = button(screen, (500, 250), str(lst[44]))
    b46 = button(screen, (000, 312), str(lst[45]))
    b47 = button(screen, (62 , 312), str(lst[46]))
    b48 = button(screen, (124, 312), str(lst[47]))
    b49 = button(screen, (188, 312), str(lst[48]))
    b50 = button(screen, (250, 312), str(lst[49]))
    b51 = button(screen, (312, 312), str(lst[50]))
    b52 = button(screen, (376, 312), str(lst[51]))
    b53 = button(screen, (438, 312), str(lst[52]))
    b54 = button(screen, (500, 312), str(lst[53]))
    b55 = button(screen, (000, 376), str(lst[54]))
    b56 = button(screen, (62 , 376), str(lst[55]))
    b57 = button(screen, (124, 376), str(lst[56]))
    b58 = button(screen, (188, 376), str(lst[57]))
    b59 = button(screen, (250, 376), str(lst[58]))
    b60 = button(screen, (312, 376), str(lst[59]))
    b61 = button(screen, (376, 376), str(lst[60]))
    b62 = button(screen, (438, 376), str(lst[61]))
    b63 = button(screen, (500, 376), str(lst[62]))
    b64 = button(screen, (000, 438), str(lst[63]))
    b65 = button(screen, (62 , 438), str(lst[64]))
    b66 = button(screen, (124, 438), str(lst[65]))
    b67 = button(screen, (188, 438), str(lst[66]))
    b68 = button(screen, (250, 438), str(lst[67]))
    b69 = button(screen, (312, 438), str(lst[68]))
    b70 = button(screen, (376, 438), str(lst[69]))
    b71 = button(screen, (438, 438), str(lst[70]))
    b72 = button(screen, (500, 438), str(lst[71]))
    b73 = button(screen, (000, 500), str(lst[72]))
    b74 = button(screen, (62 , 500), str(lst[73]))
    b75 = button(screen, (124, 500), str(lst[74]))
    b76 = button(screen, (188, 500), str(lst[75]))
    b77 = button(screen, (250, 500), str(lst[76]))
    b78 = button(screen, (312, 500), str(lst[77]))
    b79 = button(screen, (376, 500), str(lst[78]))
    b80 = button(screen, (438, 500), str(lst[79]))
    b81 = button(screen, (500, 500), str(lst[80]))
    reset = extra_button(screen, (150,565), "RESET")
    go = extra_button(screen, (350,565), "   GO! ")
    test1 = extra_button(screen, (10,565), "Test 1")

def choose_a_number(): # returns whatever number is pressed
    while True:
        for event in pygame.event.get():
            if (event.type == pygame.QUIT):
                pygame.quit()
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_ESCAPE):
                pygame.quit()
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_0 or event.key == pygame.K_KP0):
                return 0
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_1 or event.key == pygame.K_KP1):
                return 1
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_2 or event.key == pygame.K_KP2):
                return 2
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_3 or event.key == pygame.K_KP3):
                return 3
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_4 or event.key == pygame.K_KP4):
                return 4
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_5 or event.key == pygame.K_KP5):
                return 5
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_6 or event.key == pygame.K_KP6):
                return 6
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_7 or event.key == pygame.K_KP7):
                return 7
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_8 or event.key == pygame.K_KP8):
                return 8
            if event.type == pygame.KEYDOWN and (event.key == pygame.K_9 or event.key == pygame.K_KP9):
                return 9

def solver(input_list):
    working_list = []
    for i in range(0,81,9):
        working_list.append(input_list[i:i+9])
    algo.resolve(working_list)
    return working_list


def main(): # main function
    empty_buttons()
    lst = [0 for i in range(81)]
    print(lst)
    while True:
        for event in pygame.event.get():
            if (event.type == pygame.QUIT): # if either x in top right is clicked or esc key is pressed game closes
                pygame.quit()
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    pygame.quit()
            if event.type == pygame.MOUSEBUTTONDOWN: # updating the numbers
                if b1.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(0)
                    lst.insert(0,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(0)
                    lst.insert(0,number)
                    new_buttons(lst)
                elif b2.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(1)
                    lst.insert(1,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(1)
                    lst.insert(1,number)
                    new_buttons(lst)
                elif b3.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(2)
                    lst.insert(2,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(2)
                    lst.insert(2,number)
                    new_buttons(lst)
                elif b4.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(3)
                    lst.insert(3,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(3)
                    lst.insert(3,number)
                    new_buttons(lst)
                elif b5.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(4)
                    lst.insert(4,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(4)
                    lst.insert(4,number)
                    new_buttons(lst)
                elif b6.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(5)
                    lst.insert(5,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(5)
                    lst.insert(5,number)
                    new_buttons(lst)
                elif b7.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(6)
                    lst.insert(6,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(6)
                    lst.insert(6,number)
                    new_buttons(lst) 
                elif b8.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(7)
                    lst.insert(7,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(7)
                    lst.insert(7,number)
                    new_buttons(lst)
                elif b9.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(8)
                    lst.insert(8,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(8)
                    lst.insert(8,number)
                    new_buttons(lst)
                elif b10.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(9)
                    lst.insert(9,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(9)
                    lst.insert(9,number)
                    new_buttons(lst)
                elif b11.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(10)
                    lst.insert(10,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(10)
                    lst.insert(10,number)
                    new_buttons(lst)
                elif b12.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(11)
                    lst.insert(11,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(11)
                    lst.insert(11,number)
                    new_buttons(lst)
                elif b13.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(12)
                    lst.insert(12,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(12)
                    lst.insert(12,number)
                    new_buttons(lst)
                elif b14.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(13)
                    lst.insert(13,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(13)
                    lst.insert(13,number)
                    new_buttons(lst)
                elif b15.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(14)
                    lst.insert(14,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(14)
                    lst.insert(14,number)
                    new_buttons(lst)
                elif b16.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(15)
                    lst.insert(15,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(15)
                    lst.insert(15,number)
                    new_buttons(lst)
                elif b17.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(16)
                    lst.insert(16,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(16)
                    lst.insert(16,number)
                    new_buttons(lst)
                elif b18.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(17)
                    lst.insert(17,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(17)
                    lst.insert(17,number)
                    new_buttons(lst)
                elif b19.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(18)
                    lst.insert(18,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(18)
                    lst.insert(18,number)
                    new_buttons(lst)
                elif b20.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(19)
                    lst.insert(19,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(19)
                    lst.insert(19,number)
                    new_buttons(lst)
                elif b21.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(20)
                    lst.insert(20,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(20)
                    lst.insert(20,number)
                    new_buttons(lst)
                elif b22.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(21)
                    lst.insert(21,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(21)
                    lst.insert(21,number)
                    new_buttons(lst)
                elif b23.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(22)
                    lst.insert(22,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(22)
                    lst.insert(22,number)
                    new_buttons(lst)
                elif b24.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(23)
                    lst.insert(23,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(23)
                    lst.insert(23,number)
                    new_buttons(lst)
                elif b25.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(24)
                    lst.insert(24,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(24)
                    lst.insert(24,number)
                    new_buttons(lst)
                elif b26.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(25)
                    lst.insert(25,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(25)
                    lst.insert(25,number)
                    new_buttons(lst)
                elif b27.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(26)
                    lst.insert(26,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(26)
                    lst.insert(26,number)
                    new_buttons(lst)
                elif b28.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(27)
                    lst.insert(27,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(27)
                    lst.insert(27,number)
                    new_buttons(lst)
                elif b29.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(28)
                    lst.insert(28,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(28)
                    lst.insert(28,number)
                    new_buttons(lst)
                elif b30.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(29)
                    lst.insert(29,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(29)
                    lst.insert(29,number)
                    new_buttons(lst)
                elif b31.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(30)
                    lst.insert(30,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(30)
                    lst.insert(30,number)
                    new_buttons(lst)
                elif b32.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(31)
                    lst.insert(31,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(31)
                    lst.insert(31,number)
                    new_buttons(lst)
                elif b33.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(32)
                    lst.insert(32,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(32)
                    lst.insert(32,number)
                    new_buttons(lst)
                elif b34.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(33)
                    lst.insert(33,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(33)
                    lst.insert(33,number)
                    new_buttons(lst)
                elif b35.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(34)
                    lst.insert(34,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(34)
                    lst.insert(34,number)
                    new_buttons(lst)
                elif b36.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(35)
                    lst.insert(35,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(35)
                    lst.insert(35,number)
                    new_buttons(lst)
                elif b37.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(36)
                    lst.insert(36,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(36)
                    lst.insert(36,number)
                    new_buttons(lst)
                elif b38.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(37)
                    lst.insert(37,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(37)
                    lst.insert(37,number)
                    new_buttons(lst)
                elif b39.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(38)
                    lst.insert(38,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(38)
                    lst.insert(38,number)
                    new_buttons(lst)
                elif b40.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(39)
                    lst.insert(39,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(39)
                    lst.insert(39,number)
                    new_buttons(lst)
                elif b41.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(40)
                    lst.insert(40,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(40)
                    lst.insert(40,number)
                    new_buttons(lst)
                elif b42.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(41)
                    lst.insert(41,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(41)
                    lst.insert(41,number)
                    new_buttons(lst)
                elif b43.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(42)
                    lst.insert(42,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(42)
                    lst.insert(42,number)
                    new_buttons(lst)
                elif b44.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(43)
                    lst.insert(43,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(43)
                    lst.insert(43,number)
                    new_buttons(lst)
                elif b45.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(44)
                    lst.insert(44,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(44)
                    lst.insert(44,number)
                    new_buttons(lst)
                elif b46.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(45)
                    lst.insert(45,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(45)
                    lst.insert(45,number)
                    new_buttons(lst)
                elif b47.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(46)
                    lst.insert(46,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(46)
                    lst.insert(46,number)
                    new_buttons(lst)
                elif b48.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(47)
                    lst.insert(47,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(47)
                    lst.insert(47,number)
                    new_buttons(lst)
                elif b49.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(48)
                    lst.insert(48,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(48)
                    lst.insert(48,number)
                    new_buttons(lst)
                elif b50.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(49)
                    lst.insert(49,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(49)
                    lst.insert(49,number)
                    new_buttons(lst)
                elif b51.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(50)
                    lst.insert(50,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(50)
                    lst.insert(50,number)
                    new_buttons(lst)
                elif b52.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(51)
                    lst.insert(51,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(51)
                    lst.insert(51,number)
                    new_buttons(lst)
                elif b53.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(52)
                    lst.insert(52,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(52)
                    lst.insert(52,number)
                    new_buttons(lst)
                elif b54.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(53)
                    lst.insert(53,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(53)
                    lst.insert(53,number)
                    new_buttons(lst)
                elif b55.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(54)
                    lst.insert(54,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(54)
                    lst.insert(54,number)
                    new_buttons(lst)
                elif b56.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(55)
                    lst.insert(55,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(55)
                    lst.insert(55,number)
                    new_buttons(lst)
                elif b57.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(56)
                    lst.insert(56,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(56)
                    lst.insert(56,number)
                    new_buttons(lst)
                elif b58.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(57)
                    lst.insert(57,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(57)
                    lst.insert(57,number)
                    new_buttons(lst)
                elif b59.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(58)
                    lst.insert(58,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(58)
                    lst.insert(58,number)
                    new_buttons(lst)
                elif b60.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(59)
                    lst.insert(59,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(59)
                    lst.insert(59,number)
                    new_buttons(lst)
                elif b61.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(60)
                    lst.insert(60,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(60)
                    lst.insert(60,number)
                    new_buttons(lst)
                elif b62.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(61)
                    lst.insert(61,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(61)
                    lst.insert(61,number)
                    new_buttons(lst)
                elif b63.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(62)
                    lst.insert(62,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(62)
                    lst.insert(62,number)
                    new_buttons(lst)
                elif b64.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(63)
                    lst.insert(63,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(63)
                    lst.insert(63,number)
                    new_buttons(lst)
                elif b65.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(64)
                    lst.insert(64,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(64)
                    lst.insert(64,number)
                    new_buttons(lst)
                elif b66.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(65)
                    lst.insert(65,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(65)
                    lst.insert(65,number)
                    new_buttons(lst)
                elif b67.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(66)
                    lst.insert(66,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(66)
                    lst.insert(66,number)
                    new_buttons(lst)
                elif b68.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(67)
                    lst.insert(67,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(67)
                    lst.insert(67,number)
                    new_buttons(lst)
                elif b69.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(68)
                    lst.insert(68,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(68)
                    lst.insert(68,number)
                    new_buttons(lst)
                elif b70.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(69)
                    lst.insert(69,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(69)
                    lst.insert(69,number)
                    new_buttons(lst)
                elif b71.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(70)
                    lst.insert(70,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(70)
                    lst.insert(70,number)
                    new_buttons(lst)
                elif b72.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(71)
                    lst.insert(71,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(71)
                    lst.insert(71,number)
                    new_buttons(lst)
                elif b73.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(72)
                    lst.insert(72,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(72)
                    lst.insert(72,number)
                    new_buttons(lst)
                elif b74.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(73)
                    lst.insert(73,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(73)
                    lst.insert(73,number)
                    new_buttons(lst)
                elif b75.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(74)
                    lst.insert(74,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(74)
                    lst.insert(74,number)
                    new_buttons(lst)
                elif b76.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(75)
                    lst.insert(75,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(75)
                    lst.insert(75,number)
                    new_buttons(lst)
                elif b77.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(76)
                    lst.insert(76,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(76)
                    lst.insert(76,number)
                    new_buttons(lst)
                elif b78.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(77)
                    lst.insert(77,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(77)
                    lst.insert(77,number)
                    new_buttons(lst)
                elif b79.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(78)
                    lst.insert(78,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(78)
                    lst.insert(78,number)
                    new_buttons(lst)
                elif b80.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(79)
                    lst.insert(79,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(79)
                    lst.insert(79,number)
                    new_buttons(lst)
                elif b81.collidepoint(pygame.mouse.get_pos()):
                    lst.pop(80)
                    lst.insert(80,"_")
                    new_buttons(lst)
                    pygame.display.update()
                    number = choose_a_number()
                    lst.pop(80)
                    lst.insert(80,number)
                    new_buttons(lst)
                elif reset.collidepoint(pygame.mouse.get_pos()):
                    lst = [0 for j in range(81)]
                    empty_buttons()
                elif go.collidepoint(pygame.mouse.get_pos()):
                    give = solver(lst)
                    flattened = [
                        val for arr in give for val in arr]
                    new_buttons(flattened)
                elif test1.collidepoint(pygame.mouse.get_pos()):
                    lst = [7,8,0,4,0,0,1,2,0,6,0,0,0,7,5,0,0,9,0,0,0,6,0,1,0,7,8,0,0,7,0,4,0,2,6,0,0,0,1,0,5,0,9,3,0,9,0,4,0,6,0,0,0,5,0,7,0,3,0,0,0,1,2,1,2,0,0,0,7,4,0,0,0,4,9,2,0,6,0,0,7]
                    new_buttons(lst)
        pygame.display.update()
    pygame.quit()
 
main()

